---
- name: make sure python is installed
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: install python (redhat family)
      raw: test -e /usr/bin/python || (test -e /usr/bin/yum && yum install -y python)
      register: raw_output
      changed_when: 'raw_output.stdout != ""'

- name: configure sshd
  hosts: all
  become: yes
  roles:
    - role: willshersystems.sshd
      tags: sshd
      vars:
        sshd:
          Port: 22
          ListenAddress:
            - '0.0.0.0'
            - '::'
          Protocol: 2
          PubkeyAuthentication: yes
          PermitRootLogin: without-password
          PasswordAuthentication: no
          PermitEmptyPasswords: no
          ChallengeResponseAuthentication: no
          KerberosAuthentication: no
          KerberosOrLocalPasswd: no
          GSSAPIAuthentication: no
          AllowTcpForwarding: no
          X11Forwarding: no
          UsePrivilegeSeparation: sandbox
          StrictModes: yes
          IgnoreRhosts: yes
          IgnoreUserKnownHosts: yes
          HostbasedAuthentication: no
          TCPKeepAlive: no

- name: set variables
  hosts: all
  tags: always
  tasks:
    - name: include distro-family vars (if any)
      include_vars: '{{ item }}'
      with_first_found:
        - files:
          - '../distro_vars/{{ os_family }}.yaml'
          skip: yes  # allow the file to not exist

    - name: include distro-specific vars (if any)
      include_vars: '{{ item }}'
      with_first_found:
        - files:
          - '../distro_vars/{{ os }}.yaml'
          skip: yes  # allow the file to not exist

    - name: include distro-version-specific vars (if any)
      include_vars: '{{ item }}'
      with_first_found:
        - files:
          - '../distro_vars/{{ os }}{{ os_version }}.yaml'
          skip: yes  # allow the file to not exist

    - name: include environment vars
      include_vars: '{{ item }}'
      with_items:
        - '../env_vars/defaults.yaml'
        - '../env_vars/{{ app_env }}.yaml'

    - set_fact:
        full_app_domain: '{% if app_subdomain %}{{ app_subdomain }}.{% endif %}{{ app_domain }}'

    - when: app_env == 'prod'
      name: include production secret variables
      include_vars:
        file: ../secrets.yaml

- name: provision server
  hosts: all
  user: deploy
  become: yes
  roles:
    - role: iptables
    - when: redhat_family
      role: geerlingguy.repo-epel
    - role: base
    - role: rvm_io.ruby
      tags: ruby
    - role: nginx
      tags: nginx
    - role: rails
      tags: rails
      become_user: '{{ rails_user }}'
