---
- name: make sure user "{{ rvm1_user }}" exists
  user: name={{ rvm1_user }} state=present shell=/bin/bash  # FIXME /bin/false

- name: install build dependencies
  package: name={{ item }} state=present
  with_items: '{{ ruby_build_deps }}'

- name: Install RVM
  include: 'rvm.yml'
  become: yes
  become_user: '{{ rvm1_user }}'

- name: Install Ruby and Gems
  include: 'rubies.yml'
  become: yes
  become_user: '{{ rvm1_user }}'
